strictness: veryhigh
doc-warnings: true
test-warnings: true

ignore-patterns:
  - ^doc/conf\.py$

pep8:
  disable:
    - W391

pylint:
  disable:
    - star-args
    - missing-docstring
    - abstract-class-not-used
    - abstract-class-little-used
    - no-init
  enable:
    - fixme

  options:
    min-public-methods: 0
    max-public-methods: 30
    max-args: 10
    max-attributes: 20
    max-parents: 10
    max-locals: 20

pyflakes:
  disable:
    - F403

frosted:
  disable:
    - E103

pyroma:
  run: true
  disable:
    - PYR15

pep257:
  run: false

